/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithms.hackerrank;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class DecryptPasswordTest {

    @Test
    public void DecryptPasswordTestt1() {
        assertEquals(
                "hAck3rr4nk",
                DecryptPassword.decryptPassword("43Ah*ck0rr0nk")
        );
    }

    @Test
    public void DecryptPasswordTest2() {
        assertEquals(
                "poTaTO",
                DecryptPassword.decryptPassword("pTo*Ta*O")
        );
    }

    @Test
    public void DecryptPasswordTest3() {
        assertEquals(
                "aP1pL5e",
                DecryptPassword.decryptPassword("51Pa*0Lp*0e")
        );
    }

    @Test
    public void DecryptPasswordTest4() {
        assertEquals(
                "fElipE4lF4v1ll3",
                DecryptPassword.decryptPassword("3144Ef*liEp*0Fl*0v0ll0")
        );
    }

}
